// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ijpnngicderlvbnycdwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcG5uZ2ljZGVybHZibnljZHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTU1ODMsImV4cCI6MjA2OTg5MTU4M30.MabkmY5zrw68kP1dWDXkt1gD9VbYc0JWfdt0XRmI_Qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);